- src/ck_ht.c
Seeing the following on an RPi2 which is 32bit ARM:
> /usr/bin/cc -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -std=gnu99 -pedantic -Wall -W -Wundef -Wendif-labels -Wshadow -Wpointer-arith -Wcast-align -Wcast-qual -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -fstrict-aliasing -O2 -pipe -Wno-parentheses  -fPIC -I/root/git/ck/include -I/root/git/ck/include -D__arm__ -c -o /root/git/ck/src/ck_ht.o /root/git/ck/src/ck_ht.c
> /root/git/ck/src/ck_ht.c: In function ‘ck_ht_map_create’:
> /root/git/ck/src/ck_ht.c:175:17: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
>   map->entries = (struct ck_ht_entry *)(((uintptr_t)&map[1] + prefix +
I fixed this warning by changing `prefix` to a `uintptr_t` …
> ck_ht: Fix build warnings on 32bit platforms.

- include/gcc/arm/ck_pr.h
Commit 554e2f08 removed underscores from _CK prefixes. It missed
the arm bits, breaking the arm build (which checks for the
non-existing _CK_PR_H). Fix it.
While at it, fix the mismatch between _CK_ISB and __CK_ISB; convert
them both to CK_ISB.
Signed-off-by: Emilio G. Cota <cota@braap.org>
> arm/ck_pr: add missing conversion to CK_ namespace

- include/ck_cc.h
- include/ck_fifo.h
- include/ck_hp_fifo.h
- include/ck_pr.h
- include/gcc/arm/ck_pr.h
- include/gcc/ck_cc.h
- include/gcc/ck_pr.h
- include/gcc/ppc/ck_pr.h
- include/gcc/ppc64/ck_pr.h
- include/gcc/sparcv9/ck_pr.h
- include/gcc/x86/ck_pr.h
- include/gcc/x86_64/ck_pr.h
- src/ck_hs.c
- src/ck_ht.c
- src/ck_rhs.c
We use some macro trickery to enforce that ck_pr_store_* is actually storing the correct type into the target variable, without any actual side effects--by making the assignment into an rvalue and using a comma expression, the compiler should optimize it away.
On the load side, we simply cast the result to the type of the target variable.
There is an unsafe version of the store_ptr macro called ck_pr_store_ptr_unsafe for those times when you are _really_ sure that you know what you're doing.
This commit also updates some of the source files (ck_ht, ck_hs, ck_rhs) to use the unsafe store_ptr macro, as all of their conversions between uintptr_t and void * are invalid under the new macros.
Finally, add a CK_CC_TYPEOF macro.
Squashed commit of the following:
commit …
> Make ck_pr_store_* and ck_pr_load_* a bit more type safe.

- include/ck_sequence.h
The atomicity of the sequence number's increment is unnecessary, since
there should be only one writer at any given time. Fix it by changing
it for a regular increment + store.
Signed-off-by: Emilio G. Cota <cota@braap.org>
> ck_sequence: relax sequence increment from atomic to regular store

- include/gcc/ck_pr.h
this makes ck_pr.h safe to include in c++ with -std=c++11
> CK_PR_ACCESS:  use __typeof__ instead of typeof

- include/ck_limits.h
this should work back to at least 3.5 kernels
> ck_limits.h: assure UINT*_MAX ff are available in-kernel

- include/ck_queue.h
Singly-linked tail queue description is taken from sys/queue.h
> ck_queue: update doc: no tail queue, add STAILQ description

- regressions/ck_ht/validate/serial.c
- src/ck_ht.c
There were one place (`ck_ht_hash()` function) that did not use user-specified hash function.
First commit adds a check whether user-specified hash function is actually used,
and second commit then fixes the failing test.
> Hashtable: actually make sure to call user-specified hash function. With new regression test.

- include/gcc/ck_cc.h
GCC supports the __restrict__ qualifier in lieu of the restrict keyword (which is not available in C++). This PR redefines CK_CC_RESTRICT to use the underscored variant to enable compilation of programs using concurrencykit with G++.
> use __restrict__ under GCC to support both C++ and C

- configure
This patch adds cygwin support for concurrencykit. Now Windows users using cygwin should be able to compile and use concucrrencykit. I didn't see a configure.ac so I modified the configure script directly. The test suite was run and all the tests passed, note that this was only tested on Windows 7.
> Add cygwin support.

- configure
- include/ck_md.h.in
- include/gcc/aarch64/ck_pr.h
- include/gcc/aarch64/ck_pr_llsc.h
- include/gcc/aarch64/ck_pr_lse.h
Add a new configure option, --enable-lse, which is only effective for
the AArch64 architecture. When used, most ck_pr_* atomics will use Large
System Extensions instructions as per the ARMv8.1 specification, rather
then LL/SC instruction pairs.
> AArch64 LSE support.

- regressions/common.h
Add support for RDTSC-like timer on AArch64. This is only used by the
internal regression/benchmark test suite.
> Add AArch64 timer support to rdtsc().

- include/ck_epoch.h
- regressions/ck_epoch/validate/ck_epoch_call.c
- regressions/ck_epoch/validate/ck_epoch_poll.c
- regressions/ck_epoch/validate/ck_epoch_section.c
- regressions/ck_epoch/validate/ck_epoch_section_2.c
- regressions/ck_epoch/validate/ck_epoch_synchronize.c
- regressions/ck_epoch/validate/ck_stack.c
- regressions/ck_epoch/validate/torture.c
- src/ck_epoch.c
Several new operations have been introduced. This work is in collaboration with Hans's requests for the FreeBSD kernel.
{synchronize,barrier}_wait: Allow callbacks if no forward progress is made in write-side operations.
epoch_value: Retrieve current value of epoch instance.
epoch_end: returns true if the record is no longer active.
call_strict: MPMC dispatch into a record.
> ck_epoch: merge in res branch.

- include/ck_ring.h
With preemption, it is possible for _ck_ring_enqueue_mp to have a
snapshot of p_head so stale with respect to the later snapshot of
c_head that a comparison modulo (small) ring size will erroneously
conclude that the ring is full.
Detect that case and retry rather than failing.  We only retry when
the enqueuers have made global forward progress, so the first loop
is as lock-free as it ever was.
Bonus: the new condition should be marginally faster.
> ck_ring.h: make _ck_ring_enqueue_mp less failure happy

- include/ck_queue.h
old version would only attempt to append `head2` to `head1` if `head2` was empty.
> ck_queue: fix logic inversion in CK_STAILQ_CONCAT.

- src/ck_ht_hash.h
Annotate fall through cases in switch statements where that behavior is
desirable to quiet compiler warnings with the -Wimplicit-fallthrough
flag. The annotation format used is supported by both GCC and Clang.
Fixes #108.
> Quiet implicit fallthrough compiler warnings.

- include/ck_epoch.h
- src/ck_epoch.c
On FreeBSD in epoch(9) records are pcpu. In order to safely access them a thread disables preemption. The problem with ck_poll executing the callback directly is that we need to access the list with preemption disabled but we can't actually execute the callbacks with preemption disabled. This should populate a deferred stack which the caller can then go and execute after re-enabling preemption. I plan on committing something like this to FreeBSD tomorrowish.
> allow ck_epoch_poll to populate a deferred stack of callbacks

- include/ck_queue.h
This would allow us to identify missed CK_ macro conversions as compile-time failures rather than potentially lurking runtime failures.
> change field names so as to be distinct from those in sys/queue.h

- configure
- include/ck_md.h.in
- include/gcc/ppc/ck_pr.h
lwsync doesn't work on e500 cores. Nathan Whitehorn says it would mainly be useful on a G5 running 32b environment but may otherwise be indistinguishable on AIM cores.  Disable lwsync by default on 32-bit Power ISA, but add an option to configure so people who don't need binary portability across all cores can enjoy lwsync.
> Use sync instead of lwsync on ppc32 by default

- configure
powerpc64 is a sub type of powerpc on FreeBSD (i.e. uname -m returns 'powerpc' on both 32b and 64b ppc systems).
I fixed up ppc, arm, but this will have some additional implications for mips and riscv if we ever add those (see arch(7))
> Fix configure on FreeBSD powerpc64

- .gitignore
- include/ck_ec.h
- regressions/Makefile
- regressions/ck_ec/benchmark/Makefile
- regressions/ck_ec/benchmark/ck_ec.c
- regressions/ck_ec/validate/Makefile
- regressions/ck_ec/validate/ck_ec_smoke_test.c
- regressions/ck_ec/validate/fuzz_harness.h
- regressions/ck_ec/validate/prop_test_slow_wakeup.c
- regressions/ck_ec/validate/prop_test_timeutil_add.c
- regressions/ck_ec/validate/prop_test_timeutil_add_ns.c
- regressions/ck_ec/validate/prop_test_timeutil_cmp.c
- regressions/ck_ec/validate/prop_test_timeutil_scale.c
- regressions/ck_ec/validate/prop_test_value.c
- regressions/ck_ec/validate/prop_test_wakeup.c
- src/Makefile.in
- src/ck_ec.c
- src/ck_ec_timeutil.h
I finally convinced myself that this thing works, and will always do so reliably.
It's x86-TSO only, so I had to introduce some weirdness in the makefiles. 
~~TODO: update docs for new vtable~~
~~TODO: test the timeval internal utils~~
~~TODO: make the regression tests work on x86~~
TODONT: final style check
TODONT: man page
~~TODO: benchmarks~~
~~TODO: fix build on !linux x86oids, done, except for validate.~~
To discuss: how do we feel about the type generic macros.
I'm gonna leave the man pages for later ;)
> ck_ec: event count with OS-assisted blocking

- Makefile.in
- configure
- regressions/ck_bitmap/validate/serial.c
Basic modifications to configure, Makefile.in, and regressions testing for compatibility with Windows
Added support for MINGW64 system, fixes to typos within Makefile.in, and a change to ck_bitmap's regression to use the correct rand() function based on platform
Specifics:
configure:
+       MINGW64*)
+               SYSTEM=mingw64
+               LDFLAGS="-mthreads $LDFLAGS"
+               ;;
This is all that is needed for compilation with MSYS2 and MinGW64. Extensive testing has not been done, however, as I'm not entirely sure what to look for, as only ck_ec triggered a failed assertion (No ck_ec ops for this platform)
regressions/ck_bitmap/validate/serial.c:
-       memset(bitmap, random(), bytes);
+       memset(bitmap, common_rand(), bytes);
... more of the same replacement
Ensure …
> Basic fixes for Windows compatibility

- include/spinlock/clh.h
- include/spinlock/hclh.h
- include/spinlock/mcs.h
This PR simply adds some explicit casts to be able to compile concurrencykit spinlocks in a C++ program, errors being currently generated.
> include/spinlock: explicit casts for C++ compilation

- include/gcc/x86/ck_pr.h
setcc works with byte registers, so we want `q` to ensure
the low byte register is encodable, not the general `r`.
Fixes https://github.com/concurrencykit/ck/issues/142.
> x86/ck_pr: fix register constraint for ck_pr_foo_is_zero

- include/ck_fifo.h
This code was returning the head of the fifo as garbage during a
de-init. It should instead return the fifo->garbage value.
> ck_fifo: Return fifo->garbage at spsc deinit

- configure
- src/Makefile.in
By default, the command 'ar' is called. Is should be possible, as with
'CC', to override that value and set an own AR.
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
> Add support for setting AR

- configure
Adding a new option '--disable-static' which makes it possible to
compile ck without a static lib. In Gentoo, we wan't to give the people
the choice, if they want to build a static variant or not.
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
> Add '--disable-static' for disabeling static lib compilation

- regressions/ck_ec/benchmark/ck_ec.c
- regressions/ck_ec/validate/ck_ec_smoke_test.c
This PR reworks how futex is called in the `ck_ec` tests and benchmarks.
Presently, the wait half of the syscall is invoked like so:
```c
syscall(SYS_futex, address,
FUTEX_WAIT_BITSET, expected, deadline,
NULL, /* `val3` argument */ deadline, 0);
```
This results in the syscall failing with `EINVAL` when `deadline` is `NULL`.
```bash
FUTEX_WAIT_BITSET (since Linux 2.6.25)
This operation is like FUTEX_WAIT except that val3 is used
to provide a 32-bit bit mask to the kernel.  This bit
mask, in which at least one bit must be set, is stored in
the kernel-internal state of the waiter.  See the
description of FUTEX_WAKE_BITSET for further details.
```
I think this may cause confusion if people use the benchmark/validation code as a starting point for their `wait`/`wake` callbacks.  The …
> Rework ck_ec tests when invoking FUTEX_WAIT_BITSET

- configure
include/ck_pr.h uses CK_USE_CC_BUILTINS, not USE_CC_BUILTINS.
> configure: Fix USE_CC_BUILTINS

- include/gcc/x86/ck_pr.h
- include/gcc/x86_64/ck_pr.h
Operations on a variable of type "ptr" specify that the output operand
can be a memory address.  Most such operations specify that the output
operand is of type char, so it has width 1.  Convert these to uint64_t
on x86_64 and uint32_t on x86.
No functional change intended.  With clang 12.0.1 there is no difference
in the generated code before and after this change.
The compiler needs to know the true width of the destination operand in
some cases.  In particular, when compiling with LLVM's MemorySanitizer
enabled, the generated code updates shadow state to mark variables as
initialized (or not) at byte granularity.  When instrumenting inline
assembly, the compiler uses the width of the output operand(s) to figure
out how many bytes of shadow state to update.  When the output operand
is …
> ck_pr: fix ptr output operand widths on x86 and x86_64

- doc/ck_epoch_barrier
- doc/ck_epoch_call
- doc/ck_epoch_recycle
- doc/ck_epoch_synchronize
Small change so the docs show the third void *cl argument to ck_epoch_register.
> Update ck_epoch_register in docs to send three arguments.

- regressions/common.h
The `thread_policy_set` call in `aff_iterate` fails with
`KERN_NOT_SUPPORTED` on M1 macbooks. The reported error from the
regression tests is "Success" because `thread_policy_set` doesn't set
errno.
This patch converts `KERN_NOT_SUPPORTED` into a successful return and
sets errno to `EINVAL` on other errors.  This is ok in the regression
tests as there affinity binding is only advisory.
Fixes #186
> Ignore KERN_NOT_SUPPORTED from thread_policy_set on mach

- regressions/common.h
Didn't build everything from scratch when fixing #186 and missed
that errno.h wasn't included on mach.
> regressions/common: Add missing include for errno on mach

- include/ck_ring.h
I was getting this build error using gcc version 8.3.0
This PR fixes that error.
> Correctly return pointer from _ck_ring_enqueue_reserve_mp

- Makefile.in
- doc/Makefile.in
Preserve original timestamps when doing cp of non-built files. That allows keeping headers unmodified on package upgrades when those headers were not modified. Gzip keeps timestamps too, so do that also for manual pages.
Correct mode of shared library to be executable by everyone. Desired especially when installing by root user.
> Preserve timestamps of installed files

- include/gcc/aarch64/ck_pr.h
This is required to enable KMSAN for aarch64 on FreeBSD. It will likely also be useful for userspace code which makes use of CK and is compiled with MSAN enabled.
> ck_pr/aarch64: Specify output operands for ck_pr_md_store_*

- include/gcc/x86_64/ck_pr.h
This type of array size notation in C serves only a documentation purpose.  That the array-size documentation provided in this macro-templated inline function declaration is not correct for any of the instantiations would be a minor nit except that gcc versions that support -Wstringop-overread and/or -Wstringop-overflow use the array sizes as guidance for when to generate those warnings (errors under -Werror).
An alternative would be to change the parameter types to explicitly be pointers - this fix preserves the documentation intent.
This resolves #185.
> Correct array parameter notation in CK_PR_LOAD_2()

- configure
The intent seemed to be there, but the implementation was broken. This fix restricts the common value extraction code to operating on options (i.e., args beginning with '--'), and repairs the '*=*' case so it properly extracts the name and value.  Now CFLAGS and other variables can be successfully passed on the command line.
> configure: fix handling of name=value argument processing

- configure
Counterintuitively, the STATIC_LIB in the config summary would show a status of '0' when enabled, and '1' when not.
> configure: fix the sense of STATIC_LIB in config summary

- configure
This activates --disable-shared for use on the command line to prevent the shared library from being built.  An error message is generated if neither the shared nor static libs are enabled.
This adds a SHARED_LIB status line in the config summary that uses the same approach for value display as for STATIC_LIB in PR #220.
> configure: support disabling the shared library build

- Makefile.in
- configure
A variable EXTRA_BUILD is defined, with a default value of 'doc', that establishes additional dependencies of the 'all' make target.  This allows disabling the doc build during make / make all by passing 'EXTRA_BUILD=' on the configure command line.
This relies on the fix for name=value command line arg processing in PR #219.
> configure: provide a way to suppress the doc build when doing a make / make all

- configure
The existing behavior was to generate two headers in the source directory and copy one of them to the build directory.  Now, both headers are generated in the build directory.  This allows a single source tree to properly support multiple, independently configured out of tree builds.
Note that the terminology in this configure script is currently such that "BUILD_DIR" is actually the source dir (root of the source tree), and "P_PWD" is the build dir (root of the build products tree).
> configure: generate headers in the build directory, not the source directory

- configure
The configure script now refers to the build products directory as BUILD_DIR and the source directory as SRC_DIR.  Previously it referred to the build products directory as P_PWD and the source directory as BUILD_DIR.
> Align build and source dir terminology with common usage

- src/ck_rhs.c
Initializing a pointer with `false` triggers undefined behaviour, and this is not valid since C23. When pointer needs to be initialized to 0, `NULL` is preferred over `false`.
> initialize delta with NULL

- src/Makefile.in
This PR fixes an issue in the Makefile.in of ck. Specifically, previously, any modifications of files like include/ck_ec_timeutil.h would not trigger a rebuild of ck_ec.o. The PR fixes this by including them as additional dependencies. This addresses https://github.com/concurrencykit/ck/issues/211.
> Fix missing dependences in src/Makefile.in

- regressions/ck_ec/benchmark/ck_ec.c
- regressions/ck_ec/validate/ck_ec_smoke_test.c
This impacts only big endian architectures.
It generates error during compilation.
> Add missing cast when assigning uint to pointer

- include/gcc/aarch64/ck_pr.h
- include/gcc/aarch64/ck_pr_llsc.h
- include/gcc/riscv64/ck_pr.h
I found out that the spacing after a label definition in inline assembly at times is not consistent. 
For example, by calling CK_PR_FAS I got this inline asm code on aarch64
define internal i32 @ck_pr_fas_uint(ptr noundef %0, i32 noundef %1) #0 {
%3 = alloca ptr, align 8
%4 = alloca i32, align 4
%5 = alloca i32, align 4
%6 = alloca i32, align 4
store ptr %0, ptr %3, align 8
store i32 %1, ptr %4, align 4
%7 = load ptr, ptr %3, align 8
%8 = load i32, ptr %4, align 4
%9 = call { i32, i32 } asm sideeffect "1:ldxr ${0:w}, [$2]\0Astxr ${1:w}, ${3:w}, [$2]\0Acbnz ${1:w}, 1b\0A", "=&r,=&r,r,r,~{memory},~{cc}"(ptr %7, i32 %8) #6, !srcloc !11
%10 = extractvalue { i32, i32 } %9, 0
%11 = extractvalue { i32, i32 } %9, 1
store i32 %10, ptr %5, align 4
store i32 %11, ptr %6, align 4
%12 = load i32, ptr …
> spacing in inline asm headers

- include/gcc/arm/ck_pr.h
- include/gcc/ppc/ck_pr.h
- include/gcc/ppc64/ck_pr.h
Following [#244](https://github.com/concurrencykit/ck/pull/244)
I have noted that also for armv7 and ppc the inline asm generated does not have the proper formatting, so I have added them 
An example would be 
"1:ldrex $0, [$2];cmp   $0, $4;itt eq;strexeq $1, $3, [$2];cmpeq   $1, #1;beq   1b;", "=&r,=&r,r,r,r,0,1,~{memory},~{cc}"
Which now has the extra divider ";" after the label definition.
"1:;ldrex $0, [$2];cmp   $0, $4;itt eq;strexeq $1, $3, [$2];cmpeq   $1, #1;beq   1b;", "=&r,=&r,r,r,r,0,1,~{memory},~{cc}"
Hope this helps!
> more spacing after label definitions

- configure
powerpc64le name is used on FreeBSD.
> configure: check for powerpc64le
